### ISSUE TITLE
Additional & in Arabic “Fork & Edit on GitHub” translation

### ISSUE THREAD

**Issue by yatil** [w3c/wai-website-data#12]
Needs to be fixed here:

https://github.com/w3c/wai-website-data/blob/master/translations.yml#L169

```yaml
- en: 'Fork &amp; Edit on GitHub'
  ar: 'تفرع &amp; وتحرير على GitHub'
```

(I don’t know Arabic, maybe just removing the `&amp;` in the translation is sufficient.)

**Comment by slhenry** [comment]
I'm on it...

**Comment by slhenry** [comment]
fixed
