### ISSUE TITLE
Translations for main navigation items

### ISSUE THREAD

**Issue by yatil** [w3c/wai-website-data#17]
Please translate the following words. Change `en` to your language code and paste the translation as a comment here. Thanks!

```
en: 'Accessibility Fundamentals'
en: 'Planning & Policies'
en: 'Design & Develop'
en: 'Test & Evaluate'
en: 'Teach & Advocate'
en: 'Standards/<wbr>Guidelines'
```

Note: The `<wbr>` allows Standards/Guidelines to break into two lines on smaller screens.

**Comment by slhenry** [comment]
@cmuncharaz Would you please translate above for the main navigation links. Thank you!

**Comment by lucasnnobrega** [comment]
Hi @yatil and @slhenry ,
here are the translations for the brazilian portuguese version if is needed:

```
pt-BR: 'Fundamentos de Acessibilidade'
pt-BR: 'Planejamento e Políticas'
pt-BR: 'Design e Desenvolvimento'
pt-BR: 'Teste e Avaliação'
pt-BR: 'Ensine e Advogue'
pt-BR: 'Diretrizes/<wbr>Padrões'
```

**Comment by cmuncharaz** [comment]
@yatil, @slhenry Here's the translation into Spanish:

es: 'Fundamentos de accesibilidad'
es: 'Planificación y Políticas'
es: 'Diseño y Desarrollo'
es: 'Pruebas y Evaluación'
es: 'Formación y Apoyo'
es: 'Estándares/<wbr>Pautas'

Thank you for sharing the brazilian portuguese translation, @lucasnnobrega! That was helpful.

**Comment by remibetin** [comment]
@yatil @slhenry Here are the the translations for the french version :

```
fr: 'Fondamentaux de l'accessibilité'
fr: 'Organisation et Politiques'
fr: 'Concevoir et Développer'
fr: 'Tester et Évaluer'
fr: 'Former et Promouvoir'
fr: 'Standards/<wbr>Recommandations'
```

**Comment by shawna-slh** [comment]
Hi @frirasyidi @Kikisek @yonguilee 

Would you provide translation of these? Then we can have the main navigation translated, too! :-)

```
en: 'Accessibility Fundamentals'
en: 'Planning & Policies'
en: 'Design & Develop'
en: 'Test & Evaluate'
en: 'Teach & Advocate'
en: 'Standards/<wbr>Guidelines'
```

**Comment by Kikisek** [comment]
Czech version:

```
cs: 'Základy přístupnosti'
cs: 'Plánování a zásady'
cs: 'Návrh a vývoj'
cs: 'Testování a vyhodnocování'
cs: 'Výuka a podpora'
cs: 'Normy/<wbr>návody'
```

**Comment by yonguilee** [comment]
@shawna-slh , Here's Korean version.


```
en: '접근성 기초'
en: '계획과 정책'
en: '디자인과 개발'
en: '테스트와 평가'
en: '교육과 옹호'
en: '표준/<wbr>가이드라인'
```

**Comment by frirasyidi** [comment]
@shawna-slh and here's the Indonesian version:

en: 'Dasar-dasar Aksesibilitas'
en: 'Perencanaan & Kebijakan'
en: 'Desain & Pengembangan'
en: 'Uji & Evaluasi'
en: 'Edukasi & Advokasi'
en: 'Standar/<wbr>Pedoman'

**Comment by brennanyoung** [comment]
da: 'Grundlæggende om tilgængelighed'
da: 'Planlægning & Politikker'
da: 'Design & Udvikler'
da: 'Test & Evaluer'
da: 'Undervise og Fortale'
da: 'Standarder/<wbr>Retningslinjer'
