### ISSUE TITLE
Please add translated navigation titles

### ISSUE THREAD

**Issue by yatil** [w3c/wai-website-data#6]
Hi Shawn,

I have lost the overview on which of the many translations are current and which made it new to the videos page.

Please update the titles here to reflect the added languages: https://github.com/w3c/wai-website-data/blob/master/navigation.yml#L18 This is necessary because we cut corners, eventually the nav title should come from the files directly.

Eric

**Comment by slhenry** [comment]
Done https://github.com/w3c/wai-website-data/pull/7

/me appreciates that we cut corners to get translations out sooner. Happy to do some manual work for now.
